version: '3.8'

services:
  postgres:
    image: postgres:10
    container_name: pln-trafo-postgres
    environment:
      POSTGRES_DB: trafo_monitoring
      POSTGRES_USER: trafo_user
      POSTGRES_PASSWORD: trafo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - pln-trafo-network

  # Uncomment the following service to run the Quarkus application in Docker
  # trafo-backend:
  #   build: .
  #   container_name: pln-trafo-backend
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/trafo_monitoring
  #     QUARKUS_DATASOURCE_USERNAME: trafo_user
  #     QUARKUS_DATASOURCE_PASSWORD: trafo_password
  #   depends_on:
  #     - postgres
  #   networks:
  #     - pln-trafo-network

volumes:
  postgres_data:

networks:
  pln-trafo-network:
    driver: bridge
